feature/HW-88
deInternetJongens/Lighthouse-Utils pull request #3
Opened 2018-09-04 08:46 UTC by jordyvandomselaar

2018-09-04 11:12 UTC, maarten00 requested changes
The unit tests regarding unsupported types now fail, because Enum types are now (supposedly) supported. 

If Enum types should be supported as of now, we need to change the tests to use another unsupported type. You should also introduce some tests to test the output for a field with an Enum type.

2018-09-05 06:24 UTC, maarten00 requested changes

2018-09-05 06:24 UTC, maarten00 commented on tests/Unit/Schema/Scalars/PostalCodeTest.php
> +            [
Please add some array keys which describe the case that is being tested

2018-09-05 06:24 UTC, maarten00 commented on tests/Unit/Schema/Scalars/PostalCodeTest.php
> +                'input' => '3081 KD',
This seems to be the exact same case as the first one, this should probably be another case (if there is another case, without spaces maybe?) or just be removed.

2018-09-05 06:24 UTC, maarten00 commented on src/Schema/Scalars/PostalCode.php
> +    public $description = 'A valid postalcode with pattern [1234aa]. Example: 1234AA.';
A valid postalcode for The Netherlands

2018-09-05 06:24 UTC, maarten00 commented on src/Schema/Scalars/PostalCode.php
> +class PostalCode extends ScalarType
PostalCodeNL or something like that would be better, since this format is only valid for Dutch postal codes.

2018-09-05 07:11 UTC, kevinpijning commented on src/Schema/Scalars/PostalCode.php
> +class PostalCode extends ScalarType
Maybe this is to specific for the package. Could be a better idea to move this to your own application instead of adding it to the package

2018-09-05 07:17 UTC, jordyvandomselaar commented on tests/Unit/Schema/Scalars/PostalCodeTest.php
> +                'input' => '3081 KD',
i like having multiple tests most of the time, because having just one case could be a "lucky pass".

2018-09-05 07:18 UTC, jordyvandomselaar commented on src/Schema/Scalars/PostalCode.php
> +class PostalCode extends ScalarType
I do think it belongs in this package, but we should extend it to allow more types.

2018-09-05 08:05 UTC, maarten00 requested changes

2018-09-05 08:05 UTC, maarten00 commented on tests/Unit/Schema/Scalars/PostalCodeNlTest.php
> +            [
Please add array keys which describe the case that is being tested

2018-09-05 08:11 UTC, jordyvandomselaar commented
I've added a different unsupported type for now.

2018-09-06 06:09 UTC, maarten00 requested changes

2018-09-06 06:09 UTC, maarten00 commented on composer.json
> +    "sirprize/postal-code-validator": "^1.3"
You don't seem to be using this package, it should probably be removed

2018-09-06 06:15 UTC, maarten00 submitted a review, later dismissed

2018-09-06 06:20 UTC, maarten00 approved these changes

2018-09-06 06:40 UTC, merged